# Generated by Django 3.2.23 on 2024-01-08 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='color_label',
            field=models.TextField(blank=True),
        ),
    ]
